# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods

    pod 'MBProgressHUD', '~> 1.0.0'

end

target 'TestUIKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	common_pods
  # Pods for TestUIKit

  target 'TestUIKitTests' do
    inherit! :search_paths
    # Pods for testing
	common_pods
  end

end
